#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst_n", 1, hls_in, -1, "", "", 1),
	Port_Property("event_done", 1, hls_out, -1, "", "", 1),
	Port_Property("in_val_TVALID", 1, hls_in, 0, "axis", "in_vld", 1),
	Port_Property("out_val_TREADY", 1, hls_in, 1, "axis", "out_acc", 1),
	Port_Property("in_val_TDATA", 24, hls_in, 0, "axis", "in_data", 1),
	Port_Property("in_val_TREADY", 1, hls_out, 0, "axis", "in_acc", 1),
	Port_Property("out_val_TDATA", 24, hls_out, 1, "axis", "out_data", 1),
	Port_Property("out_val_TVALID", 1, hls_out, 1, "axis", "out_vld", 1),
	Port_Property("s_axi_control_AWVALID", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_control_AWREADY", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_control_AWADDR", 4, hls_in, -1, "", "", 1),
	Port_Property("s_axi_control_WVALID", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_control_WREADY", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_control_WDATA", 32, hls_in, -1, "", "", 1),
	Port_Property("s_axi_control_WSTRB", 4, hls_in, -1, "", "", 1),
	Port_Property("s_axi_control_ARVALID", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_control_ARREADY", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_control_ARADDR", 4, hls_in, -1, "", "", 1),
	Port_Property("s_axi_control_RVALID", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_control_RREADY", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_control_RDATA", 32, hls_out, -1, "", "", 1),
	Port_Property("s_axi_control_RRESP", 2, hls_out, -1, "", "", 1),
	Port_Property("s_axi_control_BVALID", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_control_BREADY", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_control_BRESP", 2, hls_out, -1, "", "", 1),
	Port_Property("interrupt", 1, hls_out, -1, "", "", 1),
	Port_Property("event_start", 1, hls_out, -1, "", "", 1),
	Port_Property("stall_start_ext", 1, hls_out, -1, "", "", 1),
	Port_Property("stall_done_ext", 1, hls_out, -1, "", "", 1),
	Port_Property("stall_start_str", 1, hls_out, -1, "", "", 1),
	Port_Property("stall_done_str", 1, hls_out, -1, "", "", 1),
	Port_Property("stall_start_int", 1, hls_out, -1, "", "", 1),
	Port_Property("stall_done_int", 1, hls_out, -1, "", "", 1),
};
const char* HLS_Design_Meta::dut_name = "unary";
