catch {::common::set_param -quiet hls.xocc.mode csynth};
# 
# HLS run script generated by v++ compiler
# 

open_project unary
set_top unary
# v++ -g, -D, -I, --advanced.prop kernel.unary.kernel_flags
add_files "/home/ubuntu/samml_fpga/hw/src/unary.cpp" -cflags " -g -I /home/ubuntu/samml_fpga/hw/src"
open_solution -flow_target vitis solution
set_part xcvu47p-fsvh2892-2LV-e
create_clock -period 75.050000MHz -name default
# v++ -g or --profile_kernel stall
config_rtl -kernel_profile
# v++ --advanced.param compiler.hlsDataflowStrictMode
config_dataflow -strict_mode warning
# v++ -g
config_debug -enable
# v++ --advanced.param compiler.deadlockDetection
config_rtl -deadlock_detection sim
# v++ --advanced.param compiler.axiDeadLockFree
config_interface -m_axi_conservative_mode=1
config_interface -m_axi_addr64
# v++ --hls.max_memory_ports
config_interface -m_axi_auto_max_ports=0
config_export -format xo -ipname unary
csynth_design
export_design
close_project
puts "HLS completed successfully"
exit
